- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
- ios/RCTMarkdownUtils.mm
This PR removes bold formatting for Markdown syntax elements.
GH_LINK
> Disable bold for syntax

- ios/MarkdownTextInputDecoratorView.mm
Fixes #139. Fixes #136.
This PR fixes the incorrect behavior of `MarkdownTextInput` when `maxHeight` is set, in particular:
1. eliminates emitting `onLayout` events on each keypress with incorrect y-axis offset
2. restores automatically scrolling to the next line once newline character is appended 
Source: https://stackoverflow.com/a/43270032/23325954
GH_LINK
> Fix calling `onScroll` multiple times with incorrect y-axis offset

- src/MarkdownTextInput.web.tsx
This PR fixes the problem with different event targets depending on markdown input content.
https://github.com/Expensify/react-native-live-markdown/issues/177
After adding `document.addEventListener('paste', yourFunction);` check if event.target is always equal to MarkdownTextInput ref.
https://github.com/Expensify/App/issues/36269
> Fix event targets returned by paste eventListeners

- src/MarkdownTextInput.web.tsx
This PR fixes how our markdown text input tracks text selection and adds `selectionStart` and `selectionEnd` variables to input ref.
https://github.com/Expensify/react-native-live-markdown/issues/173
Using reproduction code from the linked issue start changing the text selection. Verify in console if it returns correct values. Next, position your cursor at the beginning of the markdown text input and after clicking `arrow up`, verify if focus is changed into RN text input that is above
https://github.com/Expensify/App/issues/36173
> Add selectionStart and selectionEnd variables to markdown input ref 

- src/MarkdownTextInput.web.tsx
Follow up to https://github.com/Expensify/react-native-live-markdown/pull/178
[GH_LINK](https://github.com/Expensify/react-native-live-markdown/pull/178)
In your App add the following code and test if pasting text to live markdown text input doesn't throw any errors.
```javascript
document.addEventListener('paste', (e) => {
// your code
});
```
> Remove try catch from paste event listener handler

- src/MarkdownTextInput.web.tsx
> useLayoutEffect is a version of [useEffect](https://react.dev/reference/react/useEffect) that fires before the browser repaints the screen.
It's ideal for cases where dimensions are derived from a DOM element and then updates some other element before react paints the screen. These seem like good use cases.
GH_LINK
close #166
I didn't add any tests, I'll try a video comparison maybe?
> Use `useLayoutEffect` instead of `useEffect` for string parsing and height measurements

- ios/RCTBaseTextInputView+Markdown.m
See RCA in https://github.com/Expensify/react-native-live-markdown/issues/185#issuecomment-1945808008
https://github.com/Expensify/react-native-live-markdown/assets/20516055/b0d1d45c-88bc-4617-861f-405109fb57ee
Fixes #185.
> Fix `onSelectionChange` event called twice with different payload on iOS for multiline

- src/__tests__/webParser.test.tsx
This PR fixes failing tests in `webParser.test.tsx` by doing two things:
1. All `<br>` in expected strings were replaced with `\n` according to @Skalakid's recommendations
2. One assertion was updated to match the output after merging #202
GH_LINK
> Fix failing unit tests in `webParser.test.tsx`

- src/MarkdownTextInput.web.tsx
- src/web/MarkdownTextInput.css
This PR fixes diacritics not working on every browser
https://github.com/Expensify/App/issues/36942
1. Try adding a diacritic in the text input i.e. Option+u and then "a" - this should result in "ä"
2. You can now try different cases like doing it in nested blocks, at the beginning of a word, in the middle of it, or by itself.
> Diacritics fix

- example/src/App.tsx
- src/MarkdownTextInput.web.tsx
- src/web/cursorUtils.ts
- src/web/parserUtils.ts
This PR:
- adds `selection` prop support on web
- fixes `selectionStart` and `selectionEnd` variables behavior inside MarkdownTextInput ref on web
- fixes selection detection on web 
[GH_LINK](https://github.com/Expensify/App/issues/36199)
1. Start writing in MarkdownTextInput on web
2. Verify if cursor position is correct when writing casually
3. Verify if text replacement works properly. Select some text and start writing 
4. Verify if after pasting text or emojis cursor is being set in correct position
5. Add `onSelectionChange` handler to MarkdownTextInput and verify if event returns correct selection start value
6. Add `ref` to MarkdownTextInput and verify if `ref.selectionStart` and `ref.selectionEnd` returns correct  selection end value
> Add selection variables to web implementation

- src/web/parserUtils.ts
This PR fixes a couple of problems mainly:
Text replacement issue on MacOS (chrome & safari, not supported on Firefox) 
Spell-check on Chrome & safari (another PR will solve this issue on Firefox)
https://github.com/Expensify/App/issues/36188
https://github.com/Expensify/App/issues/36193
For text replacement:
1. Make sure that you have a text replacement available on your mac more info [here](https://support.apple.com/en-am/guide/mac-help/mh35735/mac) - I have ,,cu" set up to be replaced with "see you"
2. In your text input add some text like ,,hello world"
3. Now try to add the text replacement i.e. I tried writing "current", in the bug mentioned it was replaced by "see yourrent", check if that's not happening anymore
For spellcheck:
1. Try writing a word like "apple", while you're …
> Diff-based text replacing

- src/MarkdownTextInput.web.tsx
This PR changes the default behavior of Shift + Enter to be the same as when clicking Enter. Thanks to that we have control over what happens after inserting new line and `contenteditable` work the same  on all browsers
GH_LINK
1. Open example app on Safari
2. Delete whole text
3. Start entering new lines using Shift + Enter
4. Verify if cursor is correctly positioned
> Fix Shift + Enter on Safari

- src/MarkdownTextInput.web.tsx
- src/web/browserUtils.ts
- src/web/parserUtils.ts
GH_LINK
1. Add `numberOfLines` to the component i.e. `numberOfLines={5}`
2. Try adding more lines than the selected amount
3. Make sure that the cursor is visible
> Multiline scroll fix

- src/MarkdownTextInput.web.tsx
- src/web/cursorUtils.ts
This PR fix the problem with input not scrolling into view the cursor after entering the new line using `Enter` or `Shift` + `Enter`
GH_LINK
1. Set static input height
2. Add some text so you can scroll text inside markdown input
3. On the end of the input start entering newlines. Verify on all browsers if input is scrolling down so the cursor in newline is fully visible
> Fix scroll on enter

- .eslintrc.js
- src/web/cursorUtils.ts
This PR fixes weird cursor / scrolling behaviour where you press `enter` and input doesn't scroll or is scrolling incorrectly
[GH_LINK](https://github.com/Expensify/react-native-live-markdown/issues/224)
Test in 2 scenarios:
1. Default example app 
2. With defined `numberOfLines` in `example/src/App.tsx`
Check how scrolling/cursor behaves when you:
1. Add `enter` in front of line of text / markdown block
2. Add `enter` after line of text / markdown block
3. Add `enter` at the end of input
4. Add `enter` at the beginning of input
https://github.com/Expensify/App/pull/38152
> Caret positioning & scrolling on `enter`

- android/src/main/java/com/expensify/livemarkdown/MarkdownStyle.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
- ios/RCTMarkdownStyle.h
- ios/RCTMarkdownStyle.mm
- ios/RCTMarkdownUtils.mm
- src/MarkdownTextInputDecoratorViewNativeComponent.ts
- src/styleUtils.ts
This PR allows to customize font size of codeblock and inline code in `MarkdownTextInput`.
<table>
<thead>
<tr>
<th>Android</th>
<th>iOS</th>
<th>Web</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="319" alt="Screenshot 2024-04-03 at 12 50 30" src="https://github.com/Expensify/react-native-live-markdown/assets/20516055/ab31c413-ee51-4577-9b35-ed13db0304ca"></td>
<td><img width="319" alt="Screenshot 2024-04-03 at 12 51 17" src="https://github.com/Expensify/react-native-live-markdown/assets/20516055/809fa56e-4f39-4bef-8c03-14eb78f4c780"></td>
<td><img width="319" alt="Screenshot 2024-04-03 at 12 55 36" src="https://github.com/Expensify/react-native-live-markdown/assets/20516055/1a5a8ea8-7970-42e7-ada9-c28e6c2e045f"></td>
</tr>
</tbody>
</table>
Change `code.fontSize` or `pre.fontSize` to 30 …
> Customize codeblock and inline code font size

- .eslintrc.js
- src/MarkdownTextInput.web.tsx
This PR fixes `onSubmitEditing` prop that wasn't updated in `handleKeyPress` function. Also this PR adds `react-hooks` plugin to .eslintrc.js
GH_LINK
https://github.com/Expensify/App/issues/39189
> Fix useCallback dependency arrays

- src/MarkdownTextInput.web.tsx
This PR fixes a problem where the selection gets improperly updated when there's multiple events occurring at once
[GH_LINK](https://github.com/Expensify/App/issues/39360)
It's difficult to test it manually in our current example setup, but a good representation of it could be done using Expensify App when you type really fast. 
It used to update the selection with a stale state resulting in cursor moving backwards a character, now this problem shouldn't happen anymore
> Fix selection positioning when typing fast

- src/MarkdownTextInput.web.tsx
This issue fixes a situation where the initial value of the input doesn't get saved into `InputHistory`, because of this it's not possible to undo the previous action
[GH_LINK](https://github.com/Expensify/App/issues/39255)
To test this remove the default value provided for our example.
1. Copy some longer text
2. Paste this text into input
3. Try to undo it with `CMD + Z`
> Fix undoing pasted text into the input

- ios/MarkdownTextInputDecoratorView.mm
This PR fixes the formatting of `MarkdownTextInput` when both `style` and `markdownStyle` are changed in a single React render on iOS.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><video src="https://github.com/Expensify/react-native-live-markdown/assets/20516055/c1aa600e-82b2-49de-a124-858365ff173b" /></td>
<td><video src="https://github.com/Expensify/react-native-live-markdown/assets/20516055/16695d1a-6fd5-4dd4-9763-f01e62f6e860" /></td>
</tr>
</tbody>
</table>
[GH_LINK](https://github.com/Expensify/App/issues/39348)
> Fix updating both styles at once on iOS

- RNLiveMarkdown.podspec
- example/ios/Podfile.lock
`react-native-live-markdown` supports React Native 0.71 and newer, but it still has logic around `install_modules_dependencies` being undefined. This method was introduced in 0.71, so we don't need the workarounds for it not existing.
Install pods and build the example App on iOS with the podspec updated.
> Simplify podspec by removing logic around `install_modules_dependencies`

- android/build.gradle
The library is always being built for all available ABIs even when the app it's being used in is only built for one. This causes it to fail on linking stage if React Native is built from source, since relevant `.so` files from React Native core don't exist. This PR adds relevant filters.
Run `yarn build:android` from the example app.
> Filter built ABIs so the library compiles when building for select ABIs

- ios/MarkdownLayoutManager.mm
- ios/RCTMarkdownUtils.h
Completely removes `backedTextInputView` and changes where it gets padding from for blockquotes. It was broken by #199.
This is a visual change. You can see that the grey block is misaligned without this.
> Fix blockquote paddings and remove `backedTextInputView`

- src/MarkdownTextInput.web.tsx
This PR add `onContentSizeChange` prop to live markdown web implementation. This is a part of a [jumping composer issue](https://github.com/Expensify/App/issues/39267) fix
GH_LINK
1. Add `onContentSizeChange` prop function
2. Console log its event. Verify if height and width are correct
https://github.com/Expensify/App/issues/39267
> Add onContentSizeChange prop

- package.json
- yarn.lock
This PR removes a dependency on `@types/underscore` in root `package.json`.
Apparently, it is sufficient to declare this dependency only in `parser/package.json`.
GH_LINK
> Remove `@types/underscore` dependency

- .github/workflows/build-ios.yml
This PR changes the cache key used for restoring iOS dependencies (Pods) and build artifacts (DerivedData).
Currently, the cache key includes a hash calculated from `example/ios/Podfile.lock`. Unfortunately, this file changes very frequently as we automatically bump patch version after each merged PR which results in updating the caches on each PR which is time-consuming.
Most likely, the only scenario where we should drop the caches is when we bump `react-native` version in our example app and that's exactly what this PR does.
GH_LINK
> Fix iOS build cache reuse

- README.md
This PR updates `README.md` so that it includes recently implemented `markdownStyle` fields.
GH_LINK
> Update default Markdown style in README

- src/MarkdownTextInput.web.tsx
- src/web/cursorUtils.ts
[GH_LINK](https://github.com/Expensify/App/issues/36071#issuecomment-2031031366)
> Fix input focusing on selection prop change

- android/src/main/java/com/expensify/livemarkdown/MarkdownTextInputDecoratorView.java
https://github.com/Expensify/App/issues/40504
1. Modify the MarkdownTextInput component in App. tsx with the following code:
```js
<MarkdownTextInput
multiline
autoCapitalize="none"
value={value}
onChangeText={(val) => {
if (val.includes(':+1:'))r {
setMarkdownStyle({emoji: {fontSize: 30}});
}
setValue(val.replaceAll(':+1:', '👍'));
}}
style={styles.input}
ref={ref}
markdownStyle={markdownStyle}
placeholder="Type here..."
onSelectionChange={(e) => setSelection(e.nativeEvent.selection)}
selection={selection}
/>
```
2. Clear the whole text
3. Enter :+1:
4. Check if the cursor is positioned correctly (after the emoji)
> Fix cursor positioning on android on markdown style change

- RNLiveMarkdown.podspec
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorState.h
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorViewComponentDescriptor.h
If a Swift file was added to the project with podspec target set to iOS 13 and lower, the app wouldn't compile and would throw `file not found` errors.
> Fix errors when compiling with Swift file on iOS lower than 14

- android/src/main/new_arch/MarkdownCommitHook.cpp
- android/src/main/new_arch/MarkdownCommitHook.h
The commit hook is updating the native state of the decorated text input on every shadow tree commit to override the default measurement method. Since the attributed string with the content of the input is also kept in the state, this was causing the state of the native `ReactEditText` to be updated on every commit, which effectively meant creating a new spannable on every commit and in turn losing the selection spans.
This PR changes the update to also set the event counter to `-1` when it doesn't change between updates, which effectively makes the java part of the state updates a no-op in those cases, similarly to how it's done in the core of RN: https://github.com/facebook/react-native/blob/67392cef3c8e036adfd9f77808419221d70f8f18/packages/react-native/ReactCommon/react/renderer/compone …
> Fix selection getting lost on Android on the new arch

- src/MarkdownTextInput.web.tsx
- src/web/InputHistory.ts
This PR fixes the bug when pasting text into composer before the page fully loads and the default history item is replaced
https://github.com/Expensify/App/issues/39255
> [!NOTE]  
> Issues are mostly reproducible in E/App
1. Reload the app
2. Paste text *quickly* into auto-focused markdown input
3. Undo it by clicking `Ctrl + Z`
4. Verify if the text was undone and if you can redo the changes
1. Open the app
2. Paste text into
3. Undo it by clicking `Ctrl + Z`
4. Paste text into
5. Undo it by clicking `Ctrl + Z`, verify if the text was undone
6. Go to step 2 and repeat
https://github.com/Expensify/react-native-live-markdown/pull/342
> Fix replacing default element in undo history

- example/src/App.tsx
- ios/RCTMarkdownUtils.mm
Sets the `NSBaselineOffsetAttributeName` of the `attributedText` based on the following formula:
```objc
CGFloat baseLineOffset = (maximumLineHeight - maximumFontLineHeight) / 2.0;
```
The text is vertically centered in the lineHeight of the TextInput (which corresponds to the height of the cursor). 
The solution was already added in facebook/react-native:
- PR [facebook/react-native#38359](https://github.com/facebook/react-native/pull/38359) fixed the issue on the Old architecture (Paper) in release [0.73.5](https://github.com/facebook/react-native/blob/02f163e4e83c3676216cd9360166e1cb0a8eda5f/packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputShadowView.mm#L161). 
- commit https://github.com/facebook/react-native/commit/70cc27c901aeb447910e30ac3ceac85990d3c16d fixed the …
> Fix TextInput vertical alignment issue when using lineHeight prop on iOS without changing Text baseline (Fabric - new arch)

- src/MarkdownTextInput.web.tsx
- src/web/cursorUtils.ts
- src/web/parserUtils.ts
Use `selection.setBaseAndExtent` instead of `selection.removeAllRanges(); selection.addRange(range)` to avoid the keyboard on Android chrome to hide
$ https://github.com/Expensify/App/issues/41137
PROPOSAL: https://github.com/Expensify/App/issues/41137#issuecomment-2121656214
Use Android chrome and go to the main page https://127.0.0.1:8082
Tap on a report
Paste any text repeatedly and note the page
Expected: The keyboard should remain open and visible after the paste. Also, the caret position must be maintained.
https://github.com/Expensify/App/pull/42622
> fix: use setBaseAndExtent instead of removeAllRanges

- src/MarkdownTextInput.web.tsx
Removed `autoFocus` from the `useEffect` deps so it only auto focus on mount.
https://github.com/Expensify/App/issues/42645
1. Add an `autoFocus` state to the example app
2. Add a new button to toggle the state
3. Press the button to toggle the state
4. If the state is true, verify the input isn't focused
Before:
https://github.com/Expensify/react-native-live-markdown/assets/50919443/74f976c0-5c3b-46d8-aeb3-80099ccba400
After:
https://github.com/Expensify/react-native-live-markdown/assets/50919443/18330d30-1e78-4a57-9b3a-909f52895b0b
> Auto focus only on mount

- ios/MarkdownTextInputDecoratorView.mm
The input is sometimes not scrollable on iOS.
$ https://github.com/Expensify/App/issues/41567
PROPOSAL: https://github.com/Expensify/App/issues/41567#issuecomment-2137792675
1. Open New Expensify and log in
2. Tap FAB > Assign task
3. Enter any title and add a long comment
4. On the confirmation screen open the the description and scroll down
5. Finish creating a task
6. Open the created task and tap the description
7. Scroll down
Expected Result:
User is able to scroll down the task description.
> Fix: correct content height in TextKit 1 compatibility mode

- src/MarkdownTextInput.web.tsx
- src/web/browserUtils.ts
https://github.com/Expensify/App/issues/42523
> Make TextInput ignore composition event on mWeb

- src/MarkdownTextInput.web.tsx
https://github.com/Expensify/App/issues/41137#issuecomment-2153777091
https://github.com/Expensify/App/issues/41137
Tested on Firefox
https://github.com/Expensify/react-native-live-markdown/assets/165644294/309c91fe-c8e6-472f-92ef-85375a233da5
https://github.com/Expensify/App/pull/42622
> fix: update contentSelection ref after text change

- src/MarkdownTextInput.web.tsx
Fix multiple text selection issues caused by #370.
https://github.com/Expensify/App/issues/43332
https://github.com/Expensify/App/issues/43312
https://github.com/Expensify/App/issues/43310
Testing steps:
- Test mention by typing `@` in chat.
- Test emoji addition at the end of text.
- Test editing comment by selecting text at the beginning of the comment and deleting it. It should not select some other text automatically.
- All the above should work as expected.
https://github.com/Expensify/react-native-live-markdown/assets/35566748/e45a2bdd-628a-49d2-bc3c-354cb50ebf12
> Fix multiple text selection issues

- src/MarkdownTextInput.web.tsx
- revert the use of contentSelection to restore cursor pos during text update to cursor jumping around funny since contentSelection ref value can get outdated.
- create func to restore cursor in the ref object
RCA: https://github.com/Expensify/App/issues/43312#issuecomment-2156740534
Solution: https://github.com/Expensify/App/issues/41137#issuecomment-2156739474
> fix: revert the functionality to restore cursor in value update hook

- src/web/parserUtils.ts
This PR changes the positioning of cursor next to an enlarged emoji so that it's in the middle vertically.
[GH_LINK](https://github.com/Expensify/App/issues/40412)
https://github.com/Expensify/App/pull/40692
1. Change `fontSize` for emoji in `StyleUtils.ts`. 
2. Check how cursor behaves next to text
N/A
> Fix emoji vertical alignment

- README.md
The README.md link to ExpensiMark was looking for an `ExpensiMark.js` file which no longer exists. Updated to `ExpensiMark.ts`
n/a
n/a
n/a
> docs: update ExpensiMark link

- RNLiveMarkdown.podspec
- example/ios/Podfile.lock
- ios/RCTMarkdownUtils.mm
Previously, we would use built-in JSC (JavaScriptCore) on iOS and Hermes on Android for running the JS parser.
This PR migrates iOS to use Hermes instead of JSC in order to align the iOS implementation with Android.
$ https://github.com/Expensify/react-native-live-markdown/issues/400
> Use Hermes instead of JSC on iOS

- example/ios/Podfile.lock
- ios/RCTMarkdownUtils.mm
This PR fixes the following crash on iOS
```
NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds
```
when returning improper ranges, in particular:
1. when passing a range with zero length, e.g. `{ start: 10, length: 0, type: 'code' }`
2. when passing a range that is longer than the string itself, e.g. `{ start: 0, length: 9999, type: 'bold' }`
GH_LINK
> Fix "Out of bounds" crash on iOS

- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
This PR fixes the following crash on Android:
GH_LINK
> Fix "setSpan ends beyond length" crash on Android

- ios/MarkdownCommitHook.mm
See: https://github.com/Expensify/App/issues/43983#issuecomment-2210501859
It's possible that the props aren't updated yet on the JS side, while the native state already is. In that case we'd drop the native state for a stale prop value which is incorrect. So we should make sure to only run this code on the first render.
https://github.com/Expensify/App/issues/43983
https://github.com/Expensify/App/issues/44185
I think its hard to add a specific test for this change.
I verified that the condition is executed on the first render.
I don't understand this point 😅
> fix: check if its first render before updating from props

- src/MarkdownTextInput.web.tsx
This PR is a part of a pasting doubled content in LM input, that was introduced in #369. We are adding the ability to not use our custom pasting logic when the default behavior is prevented. The whole fix can be found [here](https://github.com/Expensify/App/compare/main...software-mansion-labs:expensify-app-fork:%40Skalakid/bump-react-native-live-markdown) 
GH_LINK
> Fix onPaste event

- src/MarkdownTextInput.web.tsx
- src/web/cursorUtils.ts
As part of an effort to fix a long standing bug in expensify / react-native's text input I need to update the web implementation to work as the react-native's native change:
Goal: align with:
- https://github.com/facebook/react-native/pull/45248
In this PR the `onChange` event is send with the range in which the new changes occurred. The range is encoded as three values:
- `start`: The position in the new text where the changes started occuring
- `count`: The length of the newly changed text
- `before`: The length of the text before the changes.
Here are a few examples to better understand this:
- Initial: "Hello"
- Update to: "Hello**!**"
- `start`: 5 (end of Hello)
- `count`: 1 (the `!` was added)
- `before`: 0 (no text was replaced)
Second example:
- Initial: "Hello"
- Update to: …
> feat: add count/before/start info to `onChange` event

- ios/RCTMarkdownUtils.mm
This PR removes code logic that adds `NSMutableParagraphStyle` around h1 heading on iOS. This part of code is redundant as we don't set any styles on paragraphs.
Also, removing `NSMutableParagraphStyle` improves the performance when typing fast, as seen on the comparision below:
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><video src="https://github.com/user-attachments/assets/aedbebfb-07a2-482e-8456-ba1d2ffa2ad4"></td>
<td><video src="https://github.com/user-attachments/assets/11d40d30-dfbf-4f85-8a27-51a65bb32279"></td>
</tr>
</tbody>
</table>
Partially fixes https://github.com/Expensify/react-native-live-markdown/issues/417
> Remove `NSMutableParagraphStyle` for heading

- src/MarkdownTextInput.web.tsx
In this PR I added ranges to the onChange event:
- https://github.com/Expensify/react-native-live-markdown/pull/412
I forgot to clamp start to never become negative.
https://github.com/Expensify/App/issues/37896
https://github.com/Expensify/App/pull/44285
> fix(web): onChange event start negative

- ios/RCTBaseTextInputView+Markdown.mm
- ios/RCTTextInputComponentView+Markdown.mm
Emoji characters are automatically assigned an `AppleColorEmoji` `NSFont` and the original font is moved to `NSOriginalFont`.
We need to remove these attributes before comparison.
$ https://github.com/Expensify/App/issues/44495
PROPOSAL: https://github.com/Expensify/App/issues/44495#issuecomment-2197194378
1. Type text with an emoji.
2. Long press to select a word.
Expected Result:
Able to select a word.
<details>
<summary>Screen recordings</summary>
Before:
https://github.com/Expensify/react-native-live-markdown/assets/57348009/ea8ae269-b73f-46a5-96b8-d97feafb606c
After:
https://github.com/Expensify/react-native-live-markdown/assets/57348009/e6d21184-47f5-4390-b5f1-64169fa766ed
</details>
> Fix selection issue for text containing emoji

- .github/workflows/publish.yml
This is just a minor improvement to the publish workflow to eliminate unnecessary and noisy version bump PRs. We've updated branch permissions for OSBotify so he can push straight to main, which is practically equivalent to creating a PR, having another bot approve it, then merging it.
n/a
Run a publish workflow and verify that the version bump works.
n/a
> Eliminate self-approved version bump PRs

- src/MarkdownTextInput.web.tsx
Voice recognition on android wasn't working due to wrong handling of composition events (mWeb). 
This PR changes how we treat all `insertCompositionText` inputs to make sure that the text gets parsed only once the composition is over.
[GH_LINK](https://github.com/Expensify/App/issues/44394)
> Voice recognition handling

- src/web/cursorUtils.ts
$ https://github.com/Expensify/App/issues/46389
PROPOSAL: https://github.com/Expensify/App/issues/46389#issuecomment-2255658889
1. Add `overflow` and `maxHeight` attribute in: https://github.com/Expensify/react-native-live-markdown/blob/main/example/src/App.tsx#L190-L196
2. Run example web app
3. Insert multiple-line text until a scroll bar is shown on the right
4. On a new line insert a markdown text (eg. bold)
5. Hit the enter key on the keyboard
Verify that: the text input should scroll automatically down to reveal the new line.
> fix: find the caret domrect with largest bottom value

- WebExample/__tests__/utils.ts
- src/MarkdownTextInput.web.tsx
- src/web/utils/cursorUtils.ts
This PR contain follow up fixes to the bugs reported in E/App under the Live Markdown refactor PR. It changes and simplifies the selection event logic, so all cases when user selects the text are caught. To achieve this we had to remove standard `selectionStart` and `selectionEnd` props and replace them with custom `selection.start` and `selection.end`. Setting `selectionStart` and `selectionEnd` values breaks the native `onSelect` event handler
[GH_LINK](https://github.com/Expensify/App/pull/45150#issuecomment-2302793044)
1. Open example app on mobile Safari
2. Write some text
3. Double tap the word
4. Click `Cut`
5. Verify if text was cut
6. Check if cursor position is correct while using the Live Markdown Input on web
https://github.com/Expensify/App/pull/45150
> Fix cursor selection event on the web

- src/web/utils/inputUtils.ts
This PR fixes a problem with deleting whole content inside the input, by selecting whole content and pressing `Backspace`
GH_LINK
1. Open example on FireFox browser
2. Select whole content using mouse / `Ctrl + A`
3. Press `Backspace`
4. Verify if the input is empty
> Fix deleting whole content on Firefox

- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.cpp
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.h
`ShadowNodeFragment::Value` was removed in https://github.com/facebook/react-native/pull/43962. This PR gets rid of usage of it from the codebase.
GH_LINK
Make sure the library compiles and works on the new architecture.
> Don't use `ShadowNodeFragment::Value`

- src/__tests__/webParser.test.tsx
- src/commonTypes.ts
- src/web/utils/parserUtils.ts
- src/web/utils/treeUtils.ts
- types/global.d.ts
Follow-up to https://github.com/Expensify/react-native-live-markdown/pull/464.
This PR removes duplicate declarations of `MarkdownType` and `MarkdownRange` types and moves them to `commonTypes.ts`.
I also fixed the incorrect type `MarkdownMarkdownRange` in `global.d.ts` that most likely happened during web refactor which now lets me remove some casts.
I skipped making changes to `parser/index.ts` since this file will be removed in https://github.com/Expensify/react-native-live-markdown/pull/439.
GH_LINK
> Move `MarkdownType` and `MarkdownRange` to commonTypes.ts

- example/android/gradle.properties
- example/ios/Podfile
- example/ios/Podfile.lock
This PR modifies `gradle.properties` and `Podfile` in example app so that new architecture is enabled in example app by default in order to align the default development setup with with E/App config.
This change was first introduced by @WoLewicki in https://github.com/Expensify/react-native-live-markdown/pull/428 but decided to move it to a separate PR for better visibility.
GH_LINK
> Enable new arch by default in example app

- RNLiveMarkdown.podspec
- android/build.gradle
- android/src/main/cpp/CMakeLists.txt
- example/ios/Podfile.lock
This PR exposes the following values:
* `react_native_minor_version` in `RNLiveMarkdown.podspec`
* `getReactNativeMinorVersion()` in `build.gradle`
* `BuildConfig.REACT_NATIVE_MINOR_VERSION` in Java sources
* `REACT_NATIVE_MINOR_VERSION` in `CMakeLists.txt`
* `REACT_NATIVE_MINOR_VERSION` in C++ sources
GH_LINK
> Expose React Native minor version in buildscripts

- src/MarkdownTextInput.web.tsx
Voice recognition on android wasn't working due to the wrong handling of composition events (mWeb).
https://github.com/Expensify/App/issues/44394
1. Open an example app
2. Clear the output
3. Start using voice recognition and verify if the text wasn't duplicated
> Fix voice recognition on mWeb

- src/web/utils/cursorUtils.ts
- src/web/utils/parserUtils.ts
- src/web/utils/treeUtils.ts
This PR fixes the problem with too many input structure re-renders and fixes a problem with red spell check line being added too early, when still typing a word
https://github.com/user-attachments/assets/36310858-2e73-4c80-bd71-16bb265391fb
[GH_LINK](https://github.com/Expensify/App/issues/48662)
1. Open example app
2. Start typing any sentence
3. Verify if the red spell check line isn't shown while still typing a word
4. Verify if the red spell check line is being added correctly
> Fix red spell check line is shown frequently when typing

- RNLiveMarkdown.podspec
Hybrid app support as a follow-up from `react-native 0.75` upgrade - more context [here](https://github.com/Expensify/App/pull/48626#pullrequestreview-2282496318)
GH_LINK
> Add hybrid app support

- example/android/settings.gradle
We no longer need to build React Native from source so let's disable it for now.
GH_LINK
> Disable building example app from source on Android

- example/ios/Podfile.lock
- ios/RCTLiveMarkdownModule.h
This PR adds missing `NS_ASSUME_NONNULL_BEGIN` and `NS_ASSUME_NONNULL_END` macros.
GH_LINK
> Add missing `NS_ASSUME_NONNULL` macro

- src/MarkdownTextInput.web.tsx
- src/web/MarkdownTextInput.css
- src/web/utils/blockUtils.ts
This PR fixes single line Live Markdown Input on web, so the text content is always displayed in a single line.
https://github.com/Expensify/react-native-live-markdown/issues/481
1. Remove `multiline` prop from the `<MarkdownTextInput>` component or set it to `false`
2. Open the example app
3. Verify if the input behaves normally
> Fix single line input

- example/ios/Podfile.lock
- example/src/App.tsx
- example/src/PlatformInfo.tsx
- example/src/testConstants.ts
This PR adds some new buttons in the example app as well as moves platform info to a separate component along with utility functions located in a separate file.
GH_LINK
> Improve example app

- src/web/MarkdownTextInput.css
This PR aligns text inside the span on the web. During switching one of the inputs inside the E/App to `MarkdownInput` the [issue](https://github.com/Expensify/App/pull/47547#issuecomment-2346512582) with text alignment was defined -> the text alignment inside the usual and markdown inputs with the same styling looked different.
This PR updates the text alignment in span to fix the issue.
| Usual input | Markdown input without the alignment | Current PR - with alignment |
| ------------- | ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/55f74a4f-7c0c-46b4-809d-7e138e71d775)  | ![image](https://github.com/user-attachments/assets/73b0206d-030c-4f53-bb45-10694d634569)  | ![image](https://github.com/user-attachments/assets/75f09143-a5b9-4b6b-8499-aa153e86b …
> Align single line text span

- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.cpp
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.h
- cpp/react/renderer/components/RNLiveMarkdownSpec/OwningShadowNodeFragment.h
> Move `OwningShadowNodeFragment` to a separate file

- android/src/main/cpp/CMakeLists.txt
- android/src/main/new_arch/CMakeLists.txt
* Moved common prefabs outside of conditionals
* Removed unused prefabs and shared libraries (e.g. `android`, `log`, `ReactAndroid::mapbufferjni`)
* Added missing `find_package` for `fbjni` prefab
* Added missing `ReactAndroid::` prefix in prefabs
GH_LINK
> Cleanup CMakeLists.txt

- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
This PR fixes the following error on Android:
```
Exception in HostFunction: java.lang.IllegalStateException: Unsupported type: inline-image
```
GH_LINK
> Fix unsupported type inline image

- src/MarkdownTextInputDecoratorViewNativeComponent.ts
- src/styleUtils.ts
- src/web/inputElements/inlineImage.ts
This PR fixes inline image preview styling. It fixies `marginTop` property and adds `minWidth`, `minHeight` and `borderRadius` props
GH_LINK
1. Open the app and play with the styling values for `inlineImage` in `styleUtils.ts`
> Fix inline image preview styling

- src/MarkdownTextInput.web.tsx
The caret is in the wrong position after deleting forward with no characters selected.
https://github.com/Expensify/App/issues/48797
**Proposal:** https://github.com/Expensify/App/issues/48797#issuecomment-2348124289
1. Open the web examples.
2. Click in the middle of a word.
3. Press the `Delete` key.
**Expected result:** The caret position does not change.
https://github.com/user-attachments/assets/ae634a3f-2d63-454d-ac13-3024883b1556
https://github.com/user-attachments/assets/43f6df3e-42b8-4b12-b959-c0d1ad8efca0
> Fix caret position in web when deleting forward with no characters selected

- src/MarkdownTextInput.web.tsx
Add onTouchStart to MarkdownTextInput
GH_LINK
https://github.com/Expensify/App/issues/10731
> add onTouchStart

- src/MarkdownTextInput.web.tsx
- src/web/inputElements/inlineImage.ts
- src/web/utils/blockUtils.ts
This PR:
- add support for offline patterns and enable image reloading when the app becomes online again
- fix image styles after the app becomes online and input refreshes
- fix async image preview loading while the user is typing. Previously, the image was loaded infinitely until the user stopped writing
- fix image preview markdown layout when it's nested in the h1 tag
https://github.com/Expensify/App/pull/49250
1. Open an example app
2. Turn off internet connection on your device
3. Change the example image URL to something else. for example:  `https://picsum.photos/id/167/200/300`
4. Turn on internet connection
5. Verify if the image has been loaded
6. Verify image styles and size
1. Open an example app 
2. Put "#" before the inline images markdown tag
3. Verify the styles of the new …
> Inline images preview follow ups

- src/MarkdownTextInput.web.tsx
- src/web/utils/cursorUtils.ts
- src/web/utils/parserUtils.ts
This PR fixes the logic behind scrolling input's content into view while typing and pasting text
https://github.com/Expensify/App/issues/45885
1. Open the example app
2. Limit the height of the input so it's scrollable
3. Put the cursor in the middle of the input
4. Blur it
5. Scroll the content to the top or bottom
6. Click `Focus` button
7.  Verify if the content was scrolled into view
Pasting long text:
1. Paste the really long text into empty input
2. Verify if the content was scrolled into view and if the cursor at the end of pasted text is visible
> Fix scrolling cursor into view

- src/MarkdownTextInput.web.tsx
- src/web/inputElements/inlineImage.ts
- src/web/utils/parserUtils.ts
- src/web/utils/treeUtils.ts
This PR fixes:
- creating a tree structure when the input value is empty
- handling composition events
- target element for inline image previews 
https://github.com/Expensify/App/pull/49250
1. Open an example app
2. Set the default text of the input to `""`
3. Verify if `target.tree` isn't empty
1. On a device with a Samsung keyboard, start typing
2. Verify if the `onChangeText` event is being sent
1. Verify if inline image preview is being added to the correct input in the case where there are many Live Markdown Inputs on the page
> Live Markdown for web refactor follow ups

- RNLiveMarkdown.podspec
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownShadowFamilyRegistry.cpp
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownShadowFamilyRegistry.h
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.cpp
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.h
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorState.h
- cpp/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorViewComponentDescriptor.h
- cpp/react/renderer/components/RNLiveMarkdownSpec/OwningShadowNodeFragment.h
- example/ios/Podfile.lock
This PR removes the following ifdefs in `cpp/react/renderer/components/RNLiveMarkdownSpec/*.{cpp,h}` files:
```diff
-#if defined(RCT_NEW_ARCH_ENABLED) || defined(ANDROID)
```
The workaround with `|| defined(ANDROID)` was necessary because `RCT_NEW_ARCH_ENABLED` was not set when compiling autogenerated `autolinking.cpp` from `appmodules` target and there's no easy way to set additional flags.
Theoretically, we could add `#define RCT_NEW_ARCH_ENABLED 1` at the beginning of `RNLiveMarkdownSpec.h` but this solution seems a bit unstable.
Instead, all files in `cpp/react/renderer/components/` will be compiled conditionally based on whether the New Architecture is enabled or not.
On Android, there's a separate `CMakeLists.txt` in `android/src/main/new_arch`.
On iOS, there's a separate `newarch` …
> Refactor new arch ifdefs

- src/MarkdownTextInput.tsx
- src/MarkdownTextInput.web.tsx
- src/commonTypes.ts
- src/web/inputElements/inlineImage.ts
- src/web/utils/blockUtils.ts
- src/web/utils/parserUtils.ts
This PR adds support for extending specific inline image URLs with an auth token. Thanks to that, we can show all image previews without the need to display whole URL with a long auth token inside
https://github.com/Expensify/App/pull/50047#issuecomment-2391064780
https://github.com/Expensify/App/pull/50047
> Add authToken support for inline image URLs

- android/src/main/java/com/expensify/livemarkdown/MarkdownFontFamilySpan.java
This PR removes depreecated API usage in MarkdownFontFamilySpan.java caused by using deprecated class `ReactFontManager` from `com.facebook.react.views.text` package instead of `com.facebook.react.common.assets`.
See https://github.com/facebook/react-native/pull/38506 for more details.
```diff
-import com.facebook.react.views.text.ReactFontManager;
+import com.facebook.react.common.assets.ReactFontManager;
```
GH_LINK
> Fix deprecated API usage in `MarkdownFontFamilySpan`

- example/ios/Podfile.lock
- ios/RCTMarkdownUtils.mm
Just a small refactor to make things simpler.
Some notable changes:
```diff
if (start == 0 || start + length > attributedString.length) {
-  continue;
+  return;
}
```
```diff
-const auto &location = static_cast<int>(item.getProperty(rt, "start").asNumber());
+const auto &start = static_cast<int>(item.getProperty(rt, "start").asNumber());
```
```diff
-NSRange rangeForBackground = [inputString characterAtIndex:range.location] == '\n' ? NSMakeRange(range.location + 1, range.length - 1) : range;
+NSRange rangeForBackground = [[attributedString string] characterAtIndex:range.location] == '\n' ? NSMakeRange(range.location + 1, range.length - 1) : range;
```
GH_LINK
> Extract logic to `applyRangeToAttributedString:` method

- src/web/utils/cursorUtils.ts
THis PR fixies the problem with scrolling elements into view.It changes the logic to now scroll the whole line into view instead of just a child element 
https://github.com/Expensify/App/issues/50174
1. Add a height limit to the input inside the example app to make the component scrollable
2. Clear the input
3. Add newlines so the scroll bar appears on the side of the input
4. Paste emoji 
5. Verify if the emoji is fully visible
> Fix scrolling lines into view

- src/MarkdownTextInput.web.tsx
- src/web/inputElements/inlineImage.ts
This PR fixes the inline image flickering bug, when removing the line after it
https://github.com/user-attachments/assets/4e5828b8-e501-496c-aa15-a19fcaae9c6b
https://github.com/Expensify/App/pull/50047
1. Open an example app
2. Add a new line after the image
3. Hit backspace
4. Verify if the image didn't flicker
> Fix inline images flickering

- example/src/App.tsx
- src/MarkdownTextInput.tsx
- src/MarkdownTextInput.web.tsx
* Adjusted `ref` type of `MarkdownTextInput`, previously you would have to feed `TextInput` into `useRef`
Fixes: #487
> fix: adjust `MarkdownTextInput` ref type

- src/MarkdownTextInput.web.tsx
- src/web/utils/inputUtils.ts
Change type markdown native event to fix console error that shows up
https://github.com/Expensify/App/issues/51466
> fix: type markdown native event

- android/src/main/java/com/expensify/livemarkdown/spans/MarkdownEmojiSpan.java
This fixes the issue on Android that the measured emoji height doesn't match the actual height. It updates `MarkdownEmojiSpan` to apply the same unit conversion as used in `MarkdownFontSizeSpan`.
https://github.com/Expensify/react-native-live-markdown/blob/c282f64b11e8c8ea331add7a7d35d3cb57e450e0/android/src/main/java/com/expensify/livemarkdown/spans/MarkdownFontSizeSpan.java#L9
https://github.com/Expensify/App/issues/51287
Proposal: https://github.com/Expensify/App/issues/51287#issuecomment-2452955435
1. Build and run the Android example app.
2. Clear the text and insert three emojis 😀🍕🍔.
3. Verify that the emojis display completely.
4. Click Toggle emoji font size.
5. Verify that the emojis still display completely.
Before | After
-- | --
> Fix emoji font size measurement on Android

- android/src/main/new_arch/MarkdownCommitHook.cpp
This PR reduces the amount of times the state is cloned in the commit hook. If the state already has expected values, there's no need to clone it again (there's [pointer equality](https://github.com/facebook/react-native/blob/0d5c02656904ba53e12b13e54060f9476f63dc44/packages/react-native/ReactAndroid/src/main/jni/react/fabric/FabricMountingManager.cpp#L551) in the logic responsible for passing the state updates in RN).
> Optimize state updates done in the commit hook

- apple/MarkdownRange.h
- apple/MarkdownRange.mm
- apple/RCTMarkdownUtils.mm
- example/ios/Podfile.lock
This PR adds an intermediate step in formatting `NSAttributedString` on iOS. Instead of using `jsi::Value` from parser directly, first we populate `markdownRanges` array consisting of `MarkdownRange` objects. Then, we call `applyRangeToAttributedString` while iterating over the array.
The main benefit is that now we can memoize the parser output on the native side since holding `jsi::Value` is not recommended. It will also make it simpler to split the implementation into smaller parts.
GH_LINK
> Introduce `MarkdownRange` class on iOS

- android/src/main/java/com/expensify/livemarkdown/MarkdownRange.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
This PR adds an intermediate step in formatting `applyMarkdownFormatting` method on Android. Instead of using `JSONObject` obtained from parser directly, first we populate `markdownRanges` list consisting of `MarkdownRange` objects. Then, we call `applyRange` while iterating over the array.
This change will make it simpler to split the implementation into smaller parts and memoize the parser output as Java objects instead of memoizing JSON string.
GH_LINK
> Introduce `MarkdownRange` class on Android

- README.md
- example/package.json
- package-lock.json
- package.json
cc @dangrous @ntdiary 
bump expensify-common to 2.0.108 to include a more performant regex https://github.com/Expensify/expensify-common/pull/822
https://github.com/Expensify/App/issues/52475
1. Type `![test](https://camo.githubusercontent.com/4848d0f965f332077b77a1a0488c3e66b4769032104f4de6890bae218b4add8d/68747470733a2f2f70696373756d2e70686f746f732f69642f313036372f3230302f333030 )_test`
3. Verify the app doesn't crash
> bump expensify-common to 2.0.108

- apple/MarkdownParser.h
- apple/MarkdownParser.mm
- apple/RCTMarkdownUtils.mm
- example/ios/Podfile.lock
This PR moves parsing logic involving worklet runtime into a separate class called `MarkdownParser` on iOS as well as adds some memoization to avoid unnecessary work.
GH_LINK
> Move parsing logic to separate class on iOS

- android/src/main/java/com/expensify/livemarkdown/MarkdownParser.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
This PR moves `SoLoader.loadLibrary` call from `MarkdownUtils` to `MarkdownParser` which I forgot to do in https://github.com/Expensify/react-native-live-markdown/pull/560.
GH_LINK
> Move loading shared library to `MarkdownParser`

- android/src/main/java/com/expensify/livemarkdown/MarkdownFormatter.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
This PR moves formatting logic to `MarkdownFormatter` class on Android.
This contribution makes things simpler to test (if only we had tests).
GH_LINK
> Move formatting logic to separate class on Android

- apple/MarkdownLayoutManager.mm
- apple/RCTMarkdownUtils.h
- apple/RCTMarkdownUtils.mm
- example/ios/Podfile.lock
This PR removes `_blockquoteRangesAndLevels` in `RCTMarkdownUtils` in favor of storing the blockquote depth as `NSNumber` under custom attribute named `RCTLiveMarkdownBlockquoteDepth`.
This removes cohesion between `_blockquoteRangesAndLevels` and `applyRangeToAttributedString:` which I plan to move to a separate class called `MarkdownFormatter` in an upcoming PR.
It also simplifies the implementation of `MarkdownLayoutManager` where now we can use `[textStorage attribute:atIndex:effectiveRange:];` to check if given range is a blockquote and determine its depth without custom algorithms.
Partially applies https://github.com/Expensify/react-native-live-markdown/pull/520.
GH_LINK
> Use custom attribute to store blockquote depth on iOS

- android/src/main/java/com/expensify/livemarkdown/MarkdownFormatter.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownParser.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java
This PR adds systraces on Android for easier profiling.
Thanks to that I've noticed that `applyMarkdownFormatting` is executed twice per each keypress (at least `parseNative` is correctly memoized).
I will try to find a fix for that in a separate PR.
GH_LINK
> Add systraces on Android

- android/src/main/java/com/expensify/livemarkdown/MarkdownFormatter.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownParser.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownRange.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownStyle.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownTextWatcher.java
This PR adds missing `@NonNull` annotations in several files in Java sources for Android.
GH_LINK
> Add `@NonNull` annotations

- apple/MarkdownFormatter.h
- apple/MarkdownFormatter.mm
- apple/MarkdownLayoutManager.h
- apple/RCTMarkdownUtils.h
- apple/RCTMarkdownUtils.mm
- example/ios/Podfile.lock
This PR moves formatting logic to `MarkdownFormatter` class on iOS.
Apart from this, I also changed indentation from 4 to 2 spaces in the remaining code on @maksg's request.
This change is analogous to https://github.com/Expensify/react-native-live-markdown/pull/563 for Android.
GH_LINK
> Move formatting logic to separate class on iOS

- apple/MarkdownCommitHook.mm
- apple/MarkdownFormatter.h
- apple/MarkdownFormatter.mm
- apple/MarkdownParser.h
- apple/MarkdownParser.mm
- apple/RCTBackedTextFieldDelegateAdapter+Markdown.mm
- apple/RCTBaseTextInputView+Markdown.mm
- apple/RCTMarkdownUtils.h
- apple/RCTMarkdownUtils.mm
- apple/RCTTextInputComponentView+Markdown.mm
- apple/RCTUITextView+Markdown.mm
- example/ios/Podfile.lock
This PR introduces several minor changes (mostly renames) in iOS codebase:
```diff
-withAttributes:(nullable NSDictionary<NSAttributedStringKey, id>*)attributes
+withDefaultTextAttributes:(nonnull NSDictionary<NSAttributedStringKey, id> *)defaultTextAttributes
```
```diff
-parse:(NSString *)text
+parse:(nonnull NSString *)text
```
GH_LINK
> Minor improvements in iOS codebase

- README.md
- example/ios/Podfile.lock
- example/package.json
- package-lock.json
- package.json
Just a regular version bump.
GH_LINK
> Bump react-native-reanimated to 3.16.4

- src/parseExpensiMark.ts
This PR fixes parsing '&#.32;' (space HTML entity) in the codeblocks
https://github.com/Expensify/react-native-live-markdown/issues/580
> Fix codeblock text parsing

- RNLiveMarkdown.podspec
- example/ios/Podfile.lock
Fixes https://github.com/Expensify/react-native-live-markdown/issues/588.
Fixes https://github.com/Expensify/App/issues/54256.
This PR fixes failing iOS build with `USE_FRAMEWORKS=static` caused by two problems.
1. `'worklets/WorkletRuntime/WorkletRuntime.h' file not found` – this is caused by incorrect header structure in react-native-reanimated when `USE_FRAMEWORKS=static` is enabled. This is related to https://github.com/software-mansion/react-native-reanimated/pull/6614. The workaround here is to find path to `node_modules/react-native-reanimated`, append it with `apple/` or `Common/cpp/` and add them to header search paths. This needs to be fixed in react-native-reanimated; once fixed there we can remove the workaround here.
2. …
> Fix build with `USE_FRAMEWORKS=static`

- android/src/main/java/com/expensify/livemarkdown/MarkdownTextInputDecoratorView.java
Coming from this **E/App** issue:
- https://github.com/Expensify/App/issues/53645
only on **Android: Native**, the input live markdown styling was not being applied on subsequent component mount. More details can be found in the issue on why and how we went about fixing the issue.
cc @tomekzaw as you already have context on the discussions and approved the solution
- https://github.com/Expensify/App/issues/53645
**Note**: Not reproducible with the example app because it doesn't have a navigation stack and the component structure which led to the issue in **E/App**.
**E/App Tests**
1. Go to FAB > Submit expense > Manual.
2. Enter amount > Next.
3. Select a recipient.
4. Tap Description.
5. Enter text with markdown and save.
6. Tap Description again and verify that the markdown styling is …
> FIX: Android - Live markdown style not applied consistently

- apple/MarkdownFormatter.mm
- example/ios/Podfile.lock
This PR fixes line height inside blockquote on iOS.
When `lineHeight` style is set on `MarkdownTextInput`, React Native adds `NSParagraphStyle` with `minimumLineHeight` and `maximumLineHeight` to the attributed string.
In Live Markdown, blockquote indent is set using another `NSParagraphStyle` with `firstLineHeadIndent` and `headIndent`.
Currently, we create `NSParagraphStyle` using `[NSParagraphStyle new]`, ignoring the `NSParagraphStyle` created by React Native.
This PR uses the `NSParagraphStyle` set by React Native when creating `NSParagraphStyle` for blockquotes.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><video src="https://github.com/user-attachments/assets/e3dc8e3b-91c4-4fda-82dc-c540f346e2f0" /></td>
<td><video …
> Fix blockquote line height on iOS

- src/__tests__/parseExpensiMark.test.ts
- src/parseExpensiMark.ts
This PR fixes a bug where pressing enter/new line key doesn't cause the url text to be moved to a new line.
https://github.com/Expensify/App/issues/54522
> fix: return empty array instead of throwing error if text !== markdown

- src/commonTypes.ts
- src/parseExpensiMark.ts
This simple PR adds new markdown type called `mention-short`
- the new `<mention-short>` tag will be returned from ExpensiMark once this PR is merged: https://github.com/Expensify/expensify-common/pull/824
- mention short currently does not have it's own special styling
More details about short mentions can be found here: https://github.com/Expensify/App/issues/38025#issuecomment-2558138517
https://github.com/Expensify/App/issues/38025
> Add support for short mentions from ExpensiMark

- example/ios/Podfile.lock
- package-lock.json
- package.json
This PR moves `patch-package` command from `postinstall` step to `prepare` step in `package.json` so it doesn't run when `react-native-live-markdown` is installed as a dependency but still does run when installing dependencies for development in this repository.
Fixes https://github.com/Expensify/react-native-live-markdown/issues/573.
GH_LINK
> Move patch-package from postinstall to prepare

- example/src/testConstants.ts
- src/parseExpensiMark.ts
- src/web/utils/blockUtils.ts
This PR fixes the problem with triplicating syntaxes inside the Live Markdown Input, by removing range-splitting logic from the web platform and replacing it with the fix based on CSS styles. In the future, we will focus on fixing the web parser to support splitting emojis among all other styles (especially inline code block) and properly handle tag hierarchy edge cases when building HTML structure. 
https://github.com/Expensify/App/issues/55115
1. To the text that contains emojis, add italics styling, e.g. `_🥰 test 😇 test 🥹_`
2. Verify if the text has italics style and emojis don't
3. Verify if it still works when adding other styles around it, e.g. `# *~_🥰 test 😇 test 🥹_~*`
4. Verify if emojis aren't strikethrough
5. Test it with different style combinations …
> Remove splitting ranges on emojis on the web

- src/web/MarkdownTextInput.css
- src/web/utils/blockUtils.ts
- src/web/utils/parserUtils.ts
> Mention background alignment

- src/MarkdownTextInput.tsx
- src/MarkdownTextInput.web.tsx
- src/index.tsx
When you write to a shared value in the RN runtime using `sv.value = 42;` or `sv.value(42);` syntax, the call is scheduled to be run on the UI runtime. This means that the shared value doesn't update its value on other worklet runtimes.
As a workaround, instead of calling `sv.value = 42` in the RN runtime which simply calls `runOnUI` under the hood, you can call `runOnRuntime` on your own like this:
```tsx
runOnRuntime(workletRuntime, () => {
'worklet';
sv.value = 42;
})();
```
However, currently there's no way to obtain `workletRuntime`. This PR exposes `workletRuntime` used by `MarkdownTextInput` component using `getWorkletRuntime()` function.
Because worklet runtime creation is lazy (since we really shouldn't call native/turbo modules in the top-level scope so we delay the creation …
> Expose worklet runtime

- src/MarkdownTextInput.web.tsx
- src/web/utils/inputUtils.ts
In the web example app, pasting doesn’t work after typing with Samsung keyboard.
In Expensify app, pasting works, but the caret position is wrong in the case of issue https://github.com/Expensify/App/issues/40025.
When pasting, mobile browsers don’t fire the `compositionend` event, so the component handles the pasting event in composition mode,
https://github.com/Expensify/react-native-live-markdown/blob/76258f11b45d5b549f625916fc70bbb15a84df7d/src/MarkdownTextInput.web.tsx#L373-L384
and the normal process doesn’t execute.
https://github.com/Expensify/react-native-live-markdown/blob/76258f11b45d5b549f625916fc70bbb15a84df7d/src/MarkdownTextInput.web.tsx#L399
This PR fixes the issue by detecting composition mode with the `isEventComposing()` function. …
> Fix pasting in composition mode

- android/src/main/java/com/expensify/livemarkdown/MarkdownTextInputDecoratorView.java
This PR removes leftover `AssetManager` import in MarkdownTextInputDecoratorView.java.
GH_LINK
> Remove leftover `AssetManager` import

- cpp/MarkdownGlobal.cpp
This PR partially fixes the following crash on Android:
```
react-native-live-markdown/cpp/MarkdownGlobal.cpp:40: std::shared_ptr<ShareableWorklet> expensify::livemarkdown::getMarkdownWorklet(const int): assertion "worklet != nullptr" failed
```
For some reason, `getMarkdownWorklet` is called for given `parserId` after `unregisterMarkdownWorklet` is called. The reason is currently unknown and will be investigated separately. In such case, `globalMarkdownShareableWorklets[parserId]` returns `nullptr` (and also stores `nullptr` in `globalMarkdownShareableWorklets`, sic!) and the assert fails.
After this change, in such case `globalMarkdownShareableWorklets.at(parserId)` will throw an exception. The exception will be passed through C++ code and then passed to Java side where it is already …
> Use `.at()` method instead of `operator[]` for shareable worklet lookup

- android/src/main/java/com/expensify/livemarkdown/MarkdownTextInputDecoratorView.java
Currently, in `applyNewStyles` we need to store selection start and end and restore it after `setText` call using `setSelection` method.
This PR makes use of `setTextKeepState` https://developer.android.com/reference/android/widget/TextView#setTextKeepState(java.lang.CharSequence) which sets the text to be displayed but retains the cursor position.
GH_LINK
> Call `setTextKeepState` instead of `setText` and `setSelection`

- android/src/main/java/com/expensify/livemarkdown/MarkdownTextInputDecoratorView.java
This PR refactors the implementation of `applyNewStyles` method on Android.
Currently, in `applyNewStyles` we obtain the current value using `getText` method and pass it to `setText` method in order to trigger `MarkdownTextWatcher`. This works fine but can lead to infinite loop because calling `setText` (or even `setTextKeepState`) generates a selection update event. In live-markdown example app, `onSelectionChange` callback always calls `setSelection` (without comparing `start` and `end` fields so it updates the reference to `selection` state) which results in render that leads to another `applyNewStyles` call (not sure how exactly, though).
Instead, we call `applyMarkdownFormatting` which doesn't emit selection change event.
Required by …
> Eliminate `setText` call in `applyNewStyles` on Android

- src/MarkdownTextInput.tsx
@289Adam289 reported that `MarkdownTextInput` formatting does not reflect changes in parser worklet closure after a render. The reason is that currently we call `registerParser` only when `workletHash` changes (ignoring the rules of React and ESLint warning).
This PR changes the dependency array of `useMemo` so that `registerParser` is called when `props.parser` reference changes rather than only `workletHash`.
It is the responsibility of library user to properly memoize the worklet parser
Requires https://github.com/Expensify/react-native-live-markdown/pull/608.
> Fix updating parser when worklet hash doesn't change but closure does change

- apple/MarkdownParser.mm
When parser worklet is not found, `.at()` method throws `std::out_of_range` exception which currently crashes the app. This PR adds `try/catch` block around `expensify::livemarkdown::getMarkdownWorklet()` call in MarkdownParser.mm. After this change, we will skip formatting instead of crashing the app. This is only a partial fix to unify iOS and Android implementation in their current shapes. The root cause will be addressed separately.
Partially fixes https://github.com/Expensify/react-native-live-markdown/issues/609.
> Handle `std::out_of_range` exception thrown in `getMarkdownWorklet` on iOS

- example/ios/Podfile.lock
- example/package.json
- package-lock.json
- package.json
- src/__tests__/parseExpensiMark.test.ts
- src/__tests__/webParser.test.tsx
This PR bumps minimum expensify-common version in the library and its' example app
GH_LINK
> Bump minimum expensify-common version

- src/MarkdownTextInputDecoratorViewNativeComponent.ts
- src/web/utils/blockUtils.ts
This PR fixes adding border radius style to the markdowns in the single line input mode.
GH_LINK
1. Add, for example
```
mentionUser: {
borderRadius: 5,
},
```
to the `markdownStyles`
2. Change the MarkdownTextInput component to the single line mode by deactivating the `multiline` flag
3. Verify if the border radius style was applied
> Fix setting border radius on web in singleline mode

- package.json
The npm publish workflow is failing because we added provenance to our command but it seems to use case sensitive checks. We need to update the URL so that it matches the case and can pass the provenance check.
https://expensify.slack.com/archives/C06BDSWLDPB/p1739793644035839
Merge this PR
Verify that the npm publish workflow works
> Updates url to match case

- example/src/App.tsx
- src/MarkdownTextInput.web.tsx
`caretHidden` prop doesn't hide the caret on the web platform.
https://github.com/Expensify/App/pull/55704#issuecomment-2655953155
1. Open the web example
2. Focus on the input
3. Verify there is a caret shown
4. Press the "Toggle caret hidden" button
5. Focus on the input again
6. Verify there is no caret shown
https://github.com/user-attachments/assets/b0b72ee1-d46c-4a1d-a18c-d69696d2b1a2
> Add support for `caretHidden` prop

- src/MarkdownTextInput.tsx
This PR replaces type `Range` with `MarkdownRange` in order to fix TypeScript errors that occurred after bumping react-native-reanimated to 3.17.0 (but could be also unrelated).
GH_LINK
> Replace type `Range` with `MarkdownRange`

- android/build.gradle
Co-authored-by: Łukasz Kosmaty <lukasz.kosmaty@swmansion.com>
This PR fixes building RN apps with `@expensify/react-native-live-markdown` on Android after Gradle Sync.
Big kudos to @lukmccall for investigating this issue and coming up with a clever fix!
Fixes https://github.com/Expensify/react-native-live-markdown/issues/602.
> Fix linking error `error: undefined symbol: worklets::extractWorkletRuntime` on Android

- src/MarkdownTextInput.web.tsx
- src/web/inputElements/inlineImage.ts
- src/web/utils/webStyleUtils.ts
This PR fixes the problem with infinite loading indicators when two Live Markdown inputs with the same content are present. Also it changes the way how we calculate scaled image height to fix problems related to handling multiple inputs.
https://github.com/Expensify/App/issues/56739
1. Add multiple live markdown inputs that have the same input value with inline image markdown
2. Refresh the page
3. Verify if inline images are loaded in both inputs
> Fix inline images in multiple Live Markdown inputs

- apple/MarkdownTextInputDecoratorComponentView.mm
Previously, when we had to support both Paper and Fabric, we had a common implementation of `setMarkdownStyle` and `setParserId` that we used to invoke from arch-specific code. Now we can merge the logic into `updateProps` method as well as deduplicate calls to `applyNewStyles` method.
GH_LINK
> Merge `setMarkdownStyle` and `setParserId` into `updateProps`

- android/src/main/cpp/CMakeLists.txt
- android/src/main/new_arch/CMakeLists.txt
This PR removes conditionals in CMakeLists.txt for better readability and drops support for RN 0.75.
GH_LINK
> Remove support for RN 0.75 from CMakeLists.txt on Android

- RNLiveMarkdown.podspec
Previously, we would have a separate subspec for new-arch only files on iOS. Now that we only support the New Architecture, this level of separation is not needed. This PR removes `newarch` subspec. The source files are already covered by the wildcard in main spec so there's no need for any changes. Luckily, the headers in `cpp` are not nested so `#import <RNLiveMarkdown/SomeHeader.h>` still works thanks to the way how CocoaPods flattens header files in Pods.
GH_LINK
> Remove `newarch` subspec on iOS

- android/src/main/new_arch/MarkdownCommitHook.cpp
- android/src/main/new_arch/MarkdownCommitHook.h
- android/src/main/new_arch/NativeProxy.cpp
- android/src/main/new_arch/NativeProxy.h
- android/src/main/new_arch/OnLoad.cpp
This PR adds `expensify` namespace and moves already existing `livemarkdown` namespace inside.
GH_LINK
> Move `livemarkdown` namespace to `expensify` namespace on Android

- mock/index.ts
A while ago we added `getWorkletRuntime` function, but we did not add a mock for it.
Since we have mocks for other functions we should add one for this as well.
Tests should (probably) never do anything with runtime, so I'm just mocking with empty object.
Here's an example where I added this mock in Expensify and I have tests passing correctly: https://github.com/Expensify/App/pull/54037/files#diff-19689d115bb960aa8eace61946bf9acbd2d0d8ad6b4b8f67a14dd25e3b6d16a0R3
N/A
N/A
N/A
> Add basic mock for `getWorkletRuntime`

- apple/MarkdownBackedTextInputDelegate.h
- apple/MarkdownBackedTextInputDelegate.mm
- apple/MarkdownTextInputDecoratorComponentView.mm
- apple/RCTTextInputComponentView+Markdown.mm
- apple/RCTUITextView+Markdown.mm
This PR fixes cursor position (horizontal offset) in a newline after blockquote on iOS.
The incorrect position was mainly caused by two calls to `[RCTTextInputComponentView _updateTypingAttributes]` method in `RCTTextInputComponentView` logic.
The first call comes from `[RCTTextInputComponentView textInputDidChangeSelection]`. We overwrite `typingAttributes` in `[MarkdownBackedTextInputDelegate textInputDidChangeSelection]`.
The second calls comes from `[RCTTextInputComponentView _setAttributedString]`. We overwrite `typingAttributes` after calling the original method from a swizzled method.
| Before | After |
|:-:|:-:|
| <video src="https://github.com/user-attachments/assets/90935526-1bb1-47ea-8703-ddeb6d1d9dce" /> | <video src="https://github.com/user-attachments/assets/d5ac635b-59fb-4a2 …
> Fix caret offset after blockquote on iOS

- apple/MarkdownBackedTextInputDelegate.mm
- apple/RCTTextInputComponentView+Markdown.mm
This PR fixes a visual regression introduced in https://github.com/Expensify/react-native-live-markdown/pull/642 related to cursor height in empty text input with `lineHeight` set on iOS:
| Incorrect | Correct (after this PR) |
|:-:|:-:|
| <img width="281" alt="Screenshot 2025-03-18 at 12 07 30" src="https://github.com/user-attachments/assets/fd891c69-a4c2-4163-aced-eabf514ecac8" /> | <img width="279" alt="Screenshot 2025-03-18 at 12 00 41" src="https://github.com/user-attachments/assets/5838b429-278a-41e8-9bf1-d5a56f4cbfda" /> |
In https://github.com/Expensify/react-native-live-markdown/pull/642 we added logic that removes `NSParagraphStyle` from `typingAttributes` of `RCTUITextView`. However, `lineHeight` style is applied by react-native using `NSParagraphStyle` so if we can't simply …
> Fix cursor height in empty text input with line height set

- package.json
This PR eliminates the following warning during pod install:
```
[Codegen] [DEPRECATED] @expensify/react-native-live-markdown should add the 'ios.componentProvider' property in their codegenConfig
```
GH_LINK
> Add missing property `ios.componentProvider` in `codegenConfig`

- apple/MarkdownParser.mm
This change has been introduced first as a part of https://github.com/Expensify/react-native-live-markdown/pull/520.
Currently, we store `NSString *text` in `_prevText` field in `MarkdownParser` class on iOS without making a copy during its assignment. This makes it vulnerable to mutable strings if the underlying data changes in other parts of the code (like modifying `NSTextStorage` inplace). Instead, we should make our own copy to prevent unwanted behavior in the future.
GH_LINK
> Store previous text as a copy in parser on iOS

- apple/RCTTextInputComponentView+Markdown.mm
This PR fixes the variable type of `_backedTextInputView` in case of multiline `MarkdownTextInput` which should be `RCTUITextView` instead of `RCTUITextField`.
GH_LINK
> Fix type of backed text input view on iOS

- .github/workflows/build-android.yml
- .github/workflows/build-ios.yml
- .github/workflows/build-web.yml
- .github/workflows/check.yml
- .github/workflows/lint.yml
- .github/workflows/web-e2e-test.yml
Coming from https://expensify.slack.com/archives/CC7NECV4L/p1743022578963949, this pull request updates all mutable action references to use immutable commit hashes instead. This is a security measure to protect from supply chain attacks.
> Pin GitHub Actions to immutable commit SHAs

- README.md
This PR adds React Native 0.78 to the compatibility table in the README.
GH_LINK
> Add 0.78 to compatibility table in README

- apple/MarkdownBackedTextInputDelegate.mm
This PR fixes the following crash on iOS:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MarkdownBackedTextInputDelegate textInputDidPaste:withData:]: unrecognized selector sent to instance 0x304dd8d80'
```
GH_LINK
> Fix unrecognized selector `-[MarkdownBackedTextInputDelegate textInputDidPaste:withData:]` on iOS

- apple/MarkdownTextInputDecoratorShadowNode.mm
When upgrading to React Native 0.79, I encountered a build issue related to live-markdown. It turned out there was an unnecessary import using a non-existent path. 
I removed it and the example app still builds and works correctly
GH_LINK
Just build iOS example app
> Remove unused import

- android/src/main/new_arch/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.cpp
After migration to implementation based on `display: contents`, decorator shadow nodes started keeping some JNI references. In some cases, those nodes can be deallocated on the JS garbage collection thread, where the JNI context is missing, resulting in a crash. This PR fixes that by guarding the reference behind a `SafeReleaseJniRef` struct which makes sure that the thread has JNI context before invoking desctructor.
GH_LINK
> Fix crash when invoking destructor from other threads than JS

- src/MarkdownTextInput.web.tsx
- This PR implements the solution described in [this proposal](https://github.com/Expensify/App/issues/61521#issuecomment-2866029202), combined with [this suggestion](https://github.com/Expensify/App/issues/61521#issuecomment-2878112758).
- It attempts to update the `_currentlyFocusedNode` when the markdown text input receives focus.
https://github.com/Expensify/App/issues/61521
1. Go to ND
2. Login account with more chats
3. Tap search
4. Scroll the page up and down
5. Verify: In search, scrolling the page must close the keypad.
https://github.com/user-attachments/assets/4ed57083-5253-4253-80b3-943ed9737a6d
> fix: update currentlyFocusedNode on focus

- README.md
- android/src/main/java/com/expensify/livemarkdown/MarkdownFormatter.java
- android/src/main/java/com/expensify/livemarkdown/MarkdownStyle.java
- android/src/main/java/com/expensify/livemarkdown/spans/MarkdownEmojiSpan.java
- apple/MarkdownFormatter.mm
- apple/RCTMarkdownStyle.h
- apple/RCTMarkdownStyle.mm
- src/MarkdownTextInputDecoratorViewNativeComponent.ts
- src/styleUtils.ts
Reverts Expensify/react-native-live-markdown#661
This PR led to [deploy-blocker](https://github.com/Expensify/App/issues/62410) in the E/App repo
After reverting it, the emoji isn't cut off
https://github.com/user-attachments/assets/5057e6c4-6bfd-49de-8fe6-27176585f3c2
> Revert "Add font support for emojis"

- src/__tests__/parseExpensiMark.test.ts
- src/rangeUtils.ts
When emoji is wrapped with a markdown, the emoji is being formatted and we don't want that.
$ https://github.com/Expensify/App/issues/62029
1. Run the web example
2. Type `_😄_`
3. Verify the emoji is not formatted
> Prevent emoji being formatted

- android/build.gradle
@roryabraham 
Adds support support for 16KB memory page sizes on Android.
https://github.com/Expensify/App/issues/63871
Make sure the app builds.
https://github.com/Expensify/App/pull/64640
> Android: Enable 16KB memory page size support

- src/MarkdownTextInput.web.tsx
- src/__tests__/normalizeLines.test.tsx
- src/web/utils/blockUtils.ts
- src/web/utils/parserUtils.ts
This PR fixes issues with invalid cursor position on Android mWeb in cases when multiline markdown syntax is being removed. The problem lay in the current Live Markdown Input structure, where after splitting text into lines, we were merging all lines that contained ranges that go beyond the line length into one line.  Now, if the markdown type isn't marked as a multiline type (the one that can have `<br>` tags in it), we are corresponding ranges into separate lines.
https://github.com/user-attachments/assets/d56b59d1-824b-4801-9b34-f3e0c6050a70
https://github.com/Expensify/App/issues/57024
> Fix cursor position problems on mWeb

- android/src/main/new_arch/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.cpp
- android/src/main/new_arch/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.h
- apple/MarkdownTextInputDecoratorShadowNode.h
- apple/MarkdownTextInputDecoratorShadowNode.mm
https://github.com/Expensify/react-native-live-markdown/pull/707 updated the shadow node to clone the child node during initialization. This was happening too early in some paths, causing `nullptr` to be assigned to the TextInput's context container.
This PR moves the logic to a separate method, which can be invoked when the decorator node is fully initialized. It also moves the constructors implementation to the implementation files from headers.
GH_LINK
> Clone the child node only when decorator is fully initialized

- src/MarkdownTextInput.web.tsx
- src/__tests__/singleLineInputFix.test.tsx
- src/web/utils/inputUtils.ts
- src/web/utils/parserUtils.ts
Fixes https://github.com/Expensify/react-native-live-markdown/issues/716
This PR fixes a bug where `MarkdownTextInput` with `multiline={false}` incorrectly inserts spaces when users select all text and type a replacement character. The issue was caused by the library treating all text input as potentially multiline during processing, regardless of the `multiline` prop value.
**Root Cause:**
The library was adding BR elements (containing `\n` characters) and newlines during both DOM generation and text extraction phases, even for single-line inputs. These newlines then got converted to spaces during text normalization.
**Changes Made:**
- Made BR element addition conditional on `isMultiline` parameter
- Prevents unwanted newline characters in single-line inputs
- Pass `isMultiline` …
> fix: unwanted space insertion in single line markdown text input when replacing selected text

- WebExample/__tests__/styles.spec.ts
- src/web/MarkdownTextInput.css
This PR brings back placeholder styles.
https://github.com/Expensify/App/issues/69048 
and discussion https://swmansion.slack.com/archives/C049HHMV9SM/p1755884247194659
1. Have an empty markdown input
2. Placeholder should be present
> Hotfix: Bring back placeholders on web

- android/src/main/new_arch/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.cpp
`MarkdownTextInputDecoratorShadowNode.cpp` has `layout` method which first check if there is only one child returned from `getChildren`
```cpp
const auto &children = getChildren();
react_native_assert(
children.size() == 1 &&
"MarkdownTextInputDecoratorView didn't receive exactly one child");
```
and then gets the children again to extract the child
```cpp
auto child = std::static_pointer_cast<const YogaLayoutableShadowNode>(getChildren()[0]);
```
While I'm migrating Expensify/App to React Native 0.81 I stepped upon this error, which caused adhoc build to crash
```
[14:24:49]: ▸ C/C++: /home/runner/work/App/App/node_modules/@expensify/react-native-live-markdown/android/src/main/new_arch/react/renderer/components/RNLiveMarkdownSpec/MarkdownTextInputDecoratorShadowNode.cpp:164:15: error: …
```
> Fix: Android release build issue due to "unused" children variable

- src/__tests__/parseExpensiMark.test.ts
- src/commonTypes.ts
- src/rangeUtils.ts
This is a follow-up PR to the previous [fix for cursor positioning in inline code markdown.](https://github.com/Expensify/react-native-live-markdown/pull/729) Here, I introduced a mechanism that marks opening and closing syntax, and based on that, it extends the range before opening syntax and the range after closing syntax. Thanks to that, styles are continuous  
https://github.com/Expensify/App/issues/69493
1. Open the example app
2. Paste the following text:
```
_test🚀_
~🚀test~
~_tes🚀t_~
_`test🚀`_
~`🚀test`~
~_`tes🚀t`_~
```
3. Verify if strikethrough or italic styles aren't applied to any emoji
4. Verify I styles are properly applied on opening and closing syntaxes of inline code markdowns
https://github.com/Expensify/react-native-live-markdown/pull/729
> Fix applying styles for inline code syntaxes
