ios/RCTBaseTextInputView+Markdown.m
=> Fix invalid method name in comment

.github/workflows/publish.yml
This PR migrates publish.yml github action from using `npm` to `yarn`
GH_LINK
=> Change npm usage to yarn inside publish.yml

.github/workflows/publish.yml
=> Create commit after yarn version call inside publish workflow

.github/workflows/publish.yml
=> Use squash for merging PR in publish workflow

.github/workflows/publish.yml
=> Use npm publish in workflow

package.json
=> Update version to 0.1.2

.github/workflows/publish.yml
Proposed by @thienlnam 
GH_LINK
=> Publish on npm with public access

package.json
=> Update version to 0.1.3

package.json
=> Update version to 0.1.4

package.json
=> Update version to 0.1.5

package.json
=> Update version to 0.1.6

package.json
=> Update version to 0.1.7

package.json
=> Update version to 0.1.8

package.json
=> Update version to 0.1.9

package.json
=> Update version to 0.1.10

package.json
=> Update version to 0.1.11

package.json
=> Update version to 0.1.12

package.json
=> Update version to 0.1.13

package.json
=> Update version to 0.1.15

package.json
=> Update version to 0.1.16

package.json
=> Update version to 0.1.17

package.json
=> Update version to 0.1.18

package.json
=> Update version to 0.1.19

package.json
=> Update version to 0.1.20

package.json
=> Update version to 0.1.22

package.json
=> Update version to 0.1.23

package.json
=> Update version to 0.1.24

src/MarkdownTextInput.web.tsx
This PR fixes TS error that are blocking us from releasing web implementation to Expensify New Dot app
GH_LINK
=> Fix TS errors

package.json
=> Update version to 0.1.25

package.json
=> Update version to 0.1.26

package.json
=> Update version to 0.1.27

src/web/parserUtils.ts
This PR fixes clearing Markdown Text Input for exaple with `clear()` method
GH_LINK
1. Open web example
2. Click `Clear` button
3. Verify if input was cleared
=> Fix Markdown Input clearing

package.json
=> Update version to 0.1.28

package.json
=> Update version to 0.1.29

package.json
=> Update version to 0.1.30

package.json
=> Update version to 0.1.31

package.json
=> Update version to 0.1.32

src/web/parserUtils.ts
Didn't add one file to the last PR - here's a fix for it 🤦🏻‍♂️
https://github.com/Expensify/react-native-live-markdown/pull/247
=> Add missing file for caret position fix

package.json
=> Update version to 0.1.33

src/MarkdownTextInput.web.tsx, src/web/cursorUtils.ts
GH_LINK
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Open emoji picker.
4. Select any emoji.
https://github.com/Expensify/App/issues/39234#issuecomment-2027503654
=> Fix app crashing when entering the emoji

package.json
=> Update version to 0.1.35

package.json
=> Update version to 0.1.36

package.json
=> Update version to 0.1.37

package.json
=> Update version to 0.1.38

package.json
=> Update version to 0.1.39

package.json
=> Update version to 0.1.40

package.json
=> Update version to 0.1.41

package.json
=> Update version to 0.1.42

parser/__tests__/index.test.js
This PR fixes failing tests which I forgot to update in #272.
GH_LINK
=> Fix failing tests

package.json
=> Update version to 0.1.43

package.json
=> Update version to 0.1.44

package.json
=> Update version to 0.1.45

package.json
=> Update version to 0.1.46

package.json
=> Update version to 0.1.47

src/__tests__/webParser.test.tsx
This PR fixes a failing test in `webParser.test.ts`.
GH_LINK
`yarn test`
=> Fix failing test

package.json
=> Update version to 0.1.48

package.json
=> Update version to 0.1.49

package.json
=> Update version to 0.1.51

package.json
=> Update version to 0.1.52

package.json
=> Update version to 0.1.53

package.json
=> Update version to 0.1.54

package.json
=> Update version to 0.1.55

package.json
=> Update version to 0.1.56

package.json
=> Update version to 0.1.57

package.json
=> Update version to 0.1.58

package.json
=> Update version to 0.1.59

package.json
=> Update version to 0.1.60

src/MarkdownTextInput.web.tsx
This PR fix handleContentSizeChange function and add useEffect for style changes
GH_LINK
https://github.com/Expensify/App/issues/39267
=> Fix handleContentSizeChange function

package.json
=> Update version to 0.1.61

package.json
=> Update version to 0.1.64

package.json
=> Update version to 0.1.65

package.json
=> Update version to 0.1.66

package.json
=> Update version to 0.1.67

package.json
=> Update version to 0.1.68

package.json
=> Update version to 0.1.69

package.json
=> Update version to 0.1.70

package.json
=> Update version to 0.1.71

package.json
=> Update version to 0.1.72

package.json
=> Update version to 0.1.73

package.json
=> Update version to 0.1.75

package.json
=> Update version to 0.1.76

package.json
=> Update version to 0.1.77

package.json
=> Update version to 0.1.78

package.json
=> Update version to 0.1.79

package.json
=> Update version to 0.1.81

package.json
=> Update version to 0.1.82

package.json
=> Update version to 0.1.83

package.json
=> Update version to 0.1.84

package.json
=> Update version to 0.1.85

package.json
=> Update version to 0.1.86

parser/__tests__/index.test.ts, parser/index.ts, src/__tests__/webParser.test.tsx
This PR migrates markdown parser tests to TypeScript.
GH_LINK
1. Run `yarn test` and verify if all tests pass
=> Migrate markdown parser tests to TypeScript

package.json
=> Update version to 0.1.87

package.json
=> Update version to 0.1.88

package.json
=> Update version to 0.1.89

package.json
=> Update version to 0.1.90

package.json
=> Update version to 0.1.91

package.json
=> Update version to 0.1.92

package.json
=> Update version to 0.1.93

package.json
=> Update version to 0.1.94

src/web/cursorUtils.ts
I'm not the original author of this code, just cleaning up a patch that was added in https://github.com/Expensify/App/pull/44168 to fix a deploy blocker.
related to https://github.com/Expensify/App/issues/36776
n/a - already in use on prod
n/a, after this is merged we can upgrade react-native-live-markdown and remove the patch
=> Apply patch from E/App

package.json
=> Update version to 0.1.95

package.json
=> Update version to 0.1.96

package.json
=> Update version to 0.1.97

package.json
=> Update version to 0.1.99

package.json
=> Update version to 0.1.100

package.json
=> Update version to 0.1.101

package.json
=> Update version to 0.1.102

package.json
=> Update version to 0.1.103

package.json
=> Update version to 0.1.104

package.json
=> Update version to 0.1.105

package.json
=> Update version to 0.1.106

package.json
=> Update version to 0.1.107

package.json
=> Update version to 0.1.109

.github/workflows/publish.yml
Following up on https://github.com/Expensify/react-native-live-markdown/pull/446 to add a missing token to actions/checkout
n/a
Merge to test
n/a
=> Add OS_BOTIFY_COMMIT_TOKEN

src/web/utils/parserUtils.ts
In this PR we fix tree length to prevent scenarios when the start and end tree nodes can't be found
https://github.com/Expensify/App/issues/48052
If you are using iOS simulator, test using iOS keyboard (I/O > Keyboard > Connect hardware keyboard <- set to `off`)
1. Install changes in E/App
2. Enter any chat
3. in composer enter new line and than in the second line start writing emoji, fe: `:hand:` 
4. Verify if cursor is positioned correctly
https://github.com/Expensify/react-native-live-markdown/pull/394
=> Live Markdown for web follow-up 2

ios/MarkdownTextInputDecoratorComponentView.mm
PR adding `load` method needed for dynamic frameworks to work with the library. See https://github.com/facebook/react-native/pull/37274 for more information.
=> feat: add load method

android/build.gradle
This PR is a follow-up to https://github.com/Expensify/react-native-live-markdown/pull/467.
Copied from https://github.com/software-mansion/react-native-reanimated/pull/6482
GH_LINK
=> Use node resolver to locate React Native package

android/src/main/cpp/CMakeLists.txt, android/src/main/new_arch/CMakeLists.txt
This PR reformats both `CMakeLists.txt` files using Android Studio.
GH_LINK
=> Reformat CMakeLists.txt

CONTRIBUTING.md
Just a documentation change
n/a
Run the documented test steps and verify they work 😉 
n/a
=> Add documentation on live-testing with E/App

example/src/testConstants.ts, src/web/inputElements/inlineImage.ts
This PR:
- fixes broken image icon position when URL is wron
- fixes problem with too frequent structure rerenders when image was added
- adds debounce when image URL is being changed
- changes default image in example app
https://github.com/Expensify/App/pull/49250
=> Add inline images follow ups

src/web/inputElements/inlineImage.ts
This PR fixes the issue of loading multiple images with the same URL
https://github.com/Expensify/App/pull/49250#issuecomment-2355337936
1. Open example
2. Replace input content with:
```
```
3. Verify if all images were loaded
=> Fix multiple image debounce loading

src/web/utils/cursorUtils.ts, src/web/utils/treeUtils.ts
https://github.com/Expensify/App/issues/49973
1. Set default input value to `""`
2. Click on it
3. Verify if there are no console errors
=> Fix console errors on page reload when the input is empty 

android/build.gradle, android/src/main/java/com/expensify/livemarkdown/CustomFabricUIManager.java, android/src/main/java/com/expensify/livemarkdown/LiveMarkdownPackage.java, android/src/newarch/MarkdownTextInputDecoratorViewManagerSpec.java
This PR enables `-Xlint:all` warnings, treats them as errors using `-Werror` and fixes all of them, except for one which needs to be supressed.
GH_LINK
=> Add compile options `-Xlint:all` and `-Werror`

android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownBackgroundColorSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownBlockquoteSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownBoldSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownEmojiSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownFontFamilySpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownFontSizeSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownForegroundColorSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownItalicSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownLineHeightSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownStrikethroughSpan.java, android/src/main/java/com/expensify/livemarkdown/spans/MarkdownUnderlineSpan.java
Just a small refactor.
GH_LINK
=> Move span classes to separate package

README.md
This PR adds compatibility table in README.
GH_LINK
=> Add compatibility table in README

android/build.gradle
Fixes https://github.com/Expensify/react-native-live-markdown/issues/530#issuecomment-2449295543.
GH_LINK
=> Fix duplicate `libreactnative.so`

android/build.gradle
Fixes https://github.com/Expensify/react-native-live-markdown/issues/530. Partially reverts https://github.com/Expensify/react-native-live-markdown/pull/512.
GH_LINK
=> Remove `-Xlint:all -Werror` options

.github/workflows/build-ios.yml, apple/RCTMarkdownUtils.mm
This PR fixes the following build error when building example app for iOS:
```
2024-11-05T17:09:15.4301320Z npm warn exec The following package was not found and will be installed: react-native@0.76.1
2024-11-05T17:09:37.4507220Z npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
2024-11-05T17:09:37.4544630Z npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
2024-11-05T17:09:37.5857020Z npm warn deprecated …
```
=> Fix example app build for iOS

android/src/main/java/com/expensify/livemarkdown/CustomFabricUIManager.java, android/src/reactNativeVersionPatch/CustomMountingManager/latest/com/expensify/livemarkdown/CustomMountingManager.java
This PR removes unused imports on Android.
GH_LINK
=> Remove unused imports on Android

example/src/App.tsx
cc @tomekzaw 
This PR makes app content scrollable on mobile
GH_LINK
https://github.com/user-attachments/assets/cce1d573-2693-4880-9fac-acdd9b6dde25
https://github.com/user-attachments/assets/315791f9-169d-416b-9095-0146098b1323
https://github.com/user-attachments/assets/d5365ab3-6461-43ee-a84f-12f9963dad91
=> Make mobile apps scrollable

CONTRIBUTING.md, package.json
After react-native-builder-bob bump in https://github.com/Expensify/react-native-live-markdown/pull/686 web dev build in **Expensify/App** stopped working properly (https://github.com/Expensify/App/pull/63306#issuecomment-2946002328).
No issue
1. Follow the https://github.com/Expensify/react-native-live-markdown/blob/main/CONTRIBUTING.md#testing-with-expensifyapp-or-other-projects 
2. Dev env works without issues.
https://github.com/user-attachments/assets/61433068-ec58-4627-b200-8698b4e0a30c
https://github.com/user-attachments/assets/04feb1ab-c1a7-4369-a4f0-fc9db78193bd
https://github.com/Expensify/App/pull/63306
=> Fix web build after react-native-builder-bob bump

README.md
=> Remove CommonMark mention in README
